all:				FatorialServer.class FatorialClient.class

FatorialServer.class:		FatorialServer.java
				@javac FatorialServer.java

FatorialClient.class:		FatorialClient.java
				@javac FatorialClient.java

clean:
				@rm -rf *.class *~
